Split storage
Metaswitch/clearwater-heat pull request #40
Opened 2017-03-28 12:39 UTC by Ying-metaswitch

Changes to HEAT templates to use split storage architecture

2017-03-29 09:23 UTC, johadalin requested changes
I've reviewed as far as commit b636337. A lot of the changes are good, following the design. I've put a number of comments throughout that i think we should go through at some point today.
Some high level feedback so far:

* A little bit more/clearer information on what is contained in both the pull request, and in each commit, would be useful while reviewing. I think it would be worth reading over some historical pull requests, and following the github updates for a while to get a feel for how we tend to do this on the team.
* I like that you've split the changes out into logical chunks. This helps clarify it a lot. The commit messages could be a bit more descriptive about what the actual changes are, and the first of the vellum commits should probably state that it's just copying the sprout file across (otherwise it's hard to know if it should be reviewed in detail or not).
* We should talk about testing this morning, and how it should fit into the PR flow

2017-03-29 09:23 UTC, johadalin commented on ellis.yaml
> +            sprout_hostname_mgmt=sprout.__zone__:9886
Do you know what this is used for? 
I don't think you have opened traffic to this port in the security group changes/

2017-03-29 09:23 UTC, johadalin commented on ellis.yaml
> +            hs_hostname_mgmt=hs.__zone__:8886
Same as above

2017-03-29 09:23 UTC, johadalin commented on ellis.yaml
> +            cdf_identity=cdf.__zone__.com
I think you've taken these direct from the Chef setup. This is mostly fine, but i don't think all of it makes sense. For example, we don't set up a CDF as part of the Heat deployment, and so don't set up a cdf.__Zone__ DNS entry. I don't think we need to as part of this, so having it in shared config is a bit misleading.

We can have a chat about what we need here later

2017-03-29 09:23 UTC, johadalin commented on security-groups.yaml
> +        # Homestead
This, and the rule below, are for contacting the Cassandra process using Thrift. I think the other comments refer to the process being contacted, not where the traffic is coming from (Homestead, Homer); can these do the same?

2017-03-29 09:23 UTC, johadalin commented on sprout.yaml
>              DEBIAN_FRONTEND=noninteractive apt-get install sprout-node --yes --force-yes
We haven't discussed what we'll be doing about the sprout vs sprout-node package here. I don't know if we've agreed a longer term position here, but atm this will install more packages than we want

2017-03-29 09:31 UTC, Ying-metaswitch commented on sprout.yaml
>              DEBIAN_FRONTEND=noninteractive apt-get install sprout-node --yes --force-yes
Richard mentioned that in the split-storage architecture, the sprout-node will be updated to contain only Sprout, so installing node package for all nodes will work fine.

2017-04-05 10:02 UTC, Ying-metaswitch commented
New commits fixed some security group typos using error logs throw during deployment, removed some irrelevant shared config entries, and added Chronos config to Vellum. It also adds DNS server address to Chronos config.

2017-04-05 16:44 UTC, johadalin reviewed
Just a couple of comments for minor things, otherwise all looks good :+1: 

Can you also stick a brief summary of the different test scenarios you've run through, as a record? :)

2017-04-05 16:44 UTC, johadalin commented on vellum.yaml
> +            exec > >(tee -a /var/log/clearwater-heat-sprout.log) 2>&1
Think you missed this. Should be pointing to a vellum log?

2017-04-05 16:44 UTC, johadalin commented on vellum.yaml
> +            exec > >(tee -a /var/log/clearwater-heat-sprout.log) 2>&1
We should also update the log name for dime, at https://github.com/Metaswitch/clearwater-heat/pull/40/files#diff-fbfa58039a87d980a307ef70da669b18R181

2017-04-05 16:44 UTC, johadalin commented on vellum.yaml
> +    description: IP address in private signaling network
I think the changes here have got a bit confused. Don't think these entries needed changing

2017-04-05 16:44 UTC, johadalin approved these changes

2017-04-06 14:14 UTC, merged